service: decoupling-in-practice

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-north-1'}
  memorySize: ${opt:memory, 1024}
  timeout: 10
  logRetentionInDays: 7
  versionFunctions: false
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}
  apiGateway:
    minimumCompressionSize: 1024

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-plugin-aws-alerts

package:
  individually: true

custom:
  # Actually doesn't seem to work at all?
  alerts:
    dashboards: false
    definitions:
      integrationErrors:
        metric: integrationErrors
        threshold: 0
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: '{$.message = "*Error while integrating*"}'
        treatMissingData: notBreaching

functions:
  GreeterStart:
    handler: src/start.handler
    description: Greeting start
    events:
      - httpApi:
          method: GET
          path: /greetStart

  Greeter:
    handler: src/handler.handler
    description: Greeting
    events:
      - httpApi:
          method: GET
          path: /greet
    alarms:
      - integrationErrors