openapi: 3.0.0
info:
  version: 2.0.0
  title: Greeter
  description: Greet Star Wars characters.

servers:
  - url: https://RANDOM.execute-api.REGION.amazonaws.com/prod/
    description: API server

paths:
  /greet:
    get:
      description: Greet a Star Wars character.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
      parameters:
        - in: header
          name: X-Client-Version
          description: API client version to use
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 2
            format: int32

components:
  schemas:
    Greeting:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          description: The character's name.
          minLength: 2
          maxLength: 30
          pattern: ^[\w\-\s]{2,30}$
        length:
          type: integer
          description: The length of the character in centimeters.
          minimum: 1
          maximum: 300
          format: int32